### PR TITLE
Client wcf

### PR DESCRIPTION
**Pull request by iivchenko**
Provide background for client WCF

### CODE REVIEW

**Comment by mtarcha** [comment]
CRLF what it means?

**Comment by mtarcha** [comment]
Last commit - line endings just are still improving?

**Comment by iivchenko** [comment]
CRLF - windows type of line endings. 
Yep, last commit still improving line endings)

**Comment by mtarcha** [comment]
Second commit - I think it is redundant

**Comment by mtarcha** [comment]
Maybe we don't have to make Client like wcf service:
https://msdn.microsoft.com/ru-ru/library/ms731064(v=vs.110).aspx

**Pull request closed without merging**
